stages:
  - build
  - code-analysis

services:
  - name: postgres:latest
    alias: postgresql

variables:
  POSTGRES_DB: fitness
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: maroc123
  POSTGRES_HOST_AUTH_METHOD: trust
  DATABASE_HOST: postgresql  # PostgreSQL service alias
  DATABASE_PORT: 5432
  MAVEN_CLI_OPTS: "--batch-mode"



cache:
  paths:
    - .m2/repository

image: maven:3.8.6-openjdk-18


clean-and-test:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -B verify --file pom.xml
  artifacts:
    paths:
      - target/

compile:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -s settings.xml compile

install:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS install

sonarQube:
  stage: code-analysis
  script:
    - mvn $MAVEN_CLI_OPTS sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}
