stages:
  - build

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  POSTGRES_DB: your-database-name
  POSTGRES_USER: your-db-username
  POSTGRES_PASSWORD: your-db-password
  POSTGRES_HOST_AUTH_METHOD: trust
  DATABASE_HOST: postgresql
  DATABASE_PORT: 5432

cache:
  paths:
    - .m2/repository

image: maven:3.8.6-openjdk-18

compile:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

install:
  stage: build
  services:
    - name: postgres:latest
      alias: postgresql
  script:
    - mvn $MAVEN_CLI_OPTS install
  artifacts:
    paths:
      - target/
