stages:
  - build

variables:
  POSTGRES_DB: fitness
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: maroc123
  POSTGRES_HOST_AUTH_METHOD: trust
  DATABASE_HOST: postgresql
  DATABASE_PORT: 5432

cache:
  paths:
    - .m2/repository

image: maven:3.8.6-openjdk-18

build:
  stage: build
  script:
    - mvn clean compile test package verify --batch-mode
  artifacts:
    paths:
      - target/
