stages:
  - build
  - sonarqube
  - analysis

services:
  - name: postgres:latest
    alias: postgresql

variables:
  POSTGRES_DB: fitness
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: maroc123
  POSTGRES_HOST_AUTH_METHOD: trust
  DATABASE_HOST: postgresql  # PostgreSQL service alias
  DATABASE_PORT: 5432
  MAVEN_CLI_OPTS: "--batch-mode"



cache:
  paths:
    - .m2/repository

image: maven:3.8.6-openjdk-18


clean-and-test:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -B verify --file pom.xml
  artifacts:
    paths:
      - target/

compile:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -s settings.xml compile

install:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS install



sonarqube:
  stage: sonarqube
  image: docker:latest
  script:
    - docker run -d --name sonarqube-container -p 9000:9000 -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true sonarqube:latest
  only:
    - main
    - develop

analyze:
  stage: analysis
  image: maven:latest
  script:
    - mvn clean install sonar:sonar -Dsonar.host.url=http://sonarqube:9000 -Dsonar.projectKey=my-project-key -Dsonar.sources=.
  only:
    - main
    - develop


